FROM apache/airflow:2.9.0-python3.10

USER root

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk-headless \
    curl \
    wget \
    git \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

USER airflow

COPY airflow_req.txt .
RUN pip install --no-cache-dir -r airflow_req.txt