services:
  postgres: {}
  minio: {}
  spark-master: {}
  spark-worker:
    image: bitnami/spark:3.4.1
    profiles: ["production"]
  redis: {}
  airflow-init:
    image: caliweura-airflow:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.airflow
  airflow-web:
    image: caliweura-airflow:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.airflow
  airflow-scheduler:
    image: caliweura-airflow:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.airflow
  airflow-worker:
    image: caliweura-airflow:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.airflow
  zookeeper: {}
  kafka: {}

volumes:
  postgres_data:
  minio_data:
  redis_data:
  airflow_logs:
  spark_logs:

networks:
  dp_backend:
    driver: bridge
  dp_frontend:
    driver: bridge
  dp_data:
    driver: bridge
